# https://github.com/repository-settings/app

# https://github.com/gitfool/.github/blob/main/.github/settings.yml
_extends: .github

repository:
  topics: cake, build, cake-build, csharp, dotnet, docker, docker-image

branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - build
          - ci
