trigger:
  branches:
    include:
      - "**"
    exclude:
      - "dependabot/**"
pr:
  branches:
    include:
      - master

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: DotNetCoreInstaller@1
        inputs:
          version: 3.1.301
        displayName: Install dotnet

      - task: Docker@2
        inputs:
          command: login
          containerRegistry: DockerHub
        displayName: Docker login

      - bash: dotnet tool restore && dotnet cake --bootstrap && dotnet cake --verbosity=verbose --target=build
        displayName: Cake build
