trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main ]

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major

jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout source
        submodules: true

      - task: UseDotNet@2
        displayName: Install dotnet
        inputs:
          version: 6.0.101

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose
        displayName: Cake build
