trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main ]

variables:
  CAKE_SETTINGS_ENABLESCRIPTCACHE: true
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major

jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout source
        submodules: recursive

      - task: UseDotNet@2
        displayName: Install dotnet
        inputs:
          # renovate: datasource=docker depName=dotnet-sdk packageName=mcr.microsoft.com/dotnet/sdk
          version: 6.0.402

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose
        displayName: Cake build
