trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main ]

variables:
  Cake_Settings_EnableScriptCache: true
  Cake_Settings_ShowProcessCommandLine: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major

jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout source
        submodules: recursive

      - task: UseDotNet@2
        displayName: Install dotnet
        inputs:
          # renovate: datasource=dotnet depName=dotnet-sdk
          version: 7.0.100

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose
        displayName: Cake build
