trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: UseDotNet@2
        displayName: Install dotnet
        inputs:
          version: 5.0.100

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose --target=build
        displayName: Cake build
