workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: "true"
  DOCKER_HOST: tcp://docker:2375
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_NOLOGO: "true"
  DOTNET_ROLL_FORWARD: Major
  GIT_DEPTH: 0

services:
  - docker:dind

stages: [ Build ]

Linux:
  stage: Build
  tags: [ shared, linux ]
  script:
    - curl -fsSL https://get.docker.com/ | bash -s
    - curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- --version 5.0.201
    - export DOTNET_ROOT=$HOME/.dotnet && export PATH=$DOTNET_ROOT:$PATH
    - dotnet tool restore && dotnet cake --verbosity=verbose
