workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

variables:
  Cake_Settings_EnableScriptCache: "true"
  Cake_Settings_ShowProcessCommandLine: "true"
  DOCKER_HOST: tcp://docker:2375
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_NOLOGO: "true"
  DOTNET_ROLL_FORWARD: Major
  GIT_DEPTH: 0
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:dind

stages: [ build ]

build:
  stage: build
  tags: [ shared, linux ]
  script:
    - curl -fsSL https://get.docker.com/ | bash -s
    # renovate: datasource=dotnet depName=dotnet-sdk
    - curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- --version 7.0.404
    - export DOTNET_ROOT=$HOME/.dotnet && export PATH=$DOTNET_ROOT:$PATH
    - dotnet tool restore && dotnet cake --verbosity=verbose
