name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 5.0.400

      - name: Docker login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true
