name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  Cake_Settings_EnableScriptCache: true
  Cake_Settings_ShowProcessCommandLine: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: false

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.2.0
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 7.0.402

      - name: Docker login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v2.2.0
        with:
          platforms: arm64

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Export runtime
        uses: crazy-max/ghaction-github-runtime@v2.2.0

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true
